name: Version Bump
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_SECRET }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: |
          npm ci
          npm run lint
          npm test
          npm run build
  version-bump:
    needs: [test]
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_SECRET }}
      - name: "Bump version"
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          minor-wording: "feat,feature"
          patch-wording: "fix,bug,chore,style"
          major-wording: "breaking,breaking-changes,MAJOR"
          rc-wording: "rc,release-candidate,alpha,beta,preview"
          default: prerelease
          tag-prefix: "v"
          target-branch: "main"
          commit-message: "CI: bumps version to {{version}} [skip ci]"
  deploy-package:
    needs: [test, version-bump]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "refs/heads/main"
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
      - run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
