name: Version Bump
on:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - main
jobs:
  test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: |
          npm ci
          npm run lint
          npm test
  version-bump:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Bump version"
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          minor-wording: "feat,feature"
          patch-wording: "fix,bug,chore,style"
          major-wording: "breaking,breaking-changes,MAJOR"
          rc-wording: "rc,release-candidate,alpha,beta,preview"
          default: prerelease
          tag-prefix: "v"
          target-branch: "versioning"
          commit-message: "CI: bumps version to {{version}}"
